export const videoListMock = {
  kind: "youtube#videoListResponse",
  etag: "WyU0u3ngkEErBQGx_0hQK3G1AMk",
  items: [
    {
      kind: "youtube#video",
      etag: "k1Q4E9TCNZfc_ixwDl6J07o1hmo",
      id: "tRQuAiaN0HA",
      snippet: {
        publishedAt: "2022-03-16T16:01:34Z",
        channelId: "UCp0hYYBW6IMayGgR-WeoCvQ",
        title: "Pete Davidson Got Kim Kardashian’s Name Branded on His Chest",
        description:
          "Kim Kardashian talked about going Instagram official with boyfriend Pete Davidson and confirmed that he not only has “cute” tattoos dedicated to her on his body, but he got her name branded on his chest! Tune in to the show for more!\n\nSubscribe: https://youtube.com/theellenshow?sub_confirmation=1\nCheck your local listings to watch Ellen today: https://ellen.tv/3BOuzz4\n\n#KimKardashian #PeteDavidson #Ellen #TheEllenShow #EllenDeGeneres",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/tRQuAiaN0HA/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/tRQuAiaN0HA/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/tRQuAiaN0HA/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/tRQuAiaN0HA/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/tRQuAiaN0HA/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "TheEllenShow",
        tags: [
          "ellen",
          "ellen degeneres",
          "the ellen show",
          "ellen season 19",
          "ellen new season",
          "ellen final season",
          "ellen farewell season",
          "ellen tickets",
          "ellentube",
          "watch ellen",
          "ellen season premiere",
          "ellen show",
          "kim kardashian",
          "pete davidson",
          "kanye west",
          "kim kardashian work",
          "kim kardashian snl",
          "kim kardashian interview",
          "pete davidson kanye west",
          "pete davidson roast",
          "pete davidson snl",
          "kim kardashian pete davidson snl",
          "kim kardashian pete davidson kiss",
          "kim kardashian ellen",
          "pete davidson ellen",
        ],
        categoryId: "24",
        liveBroadcastContent: "none",
        localized: {
          title: "Pete Davidson Got Kim Kardashian’s Name Branded on His Chest",
          description:
            "Kim Kardashian talked about going Instagram official with boyfriend Pete Davidson and confirmed that he not only has “cute” tattoos dedicated to her on his body, but he got her name branded on his chest! Tune in to the show for more!\n\nSubscribe: https://youtube.com/theellenshow?sub_confirmation=1\nCheck your local listings to watch Ellen today: https://ellen.tv/3BOuzz4\n\n#KimKardashian #PeteDavidson #Ellen #TheEllenShow #EllenDeGeneres",
        },
        defaultAudioLanguage: "en",
      },
      contentDetails: {
        duration: "PT4M3S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "1693078",
        likeCount: "31669",
        favoriteCount: "0",
        commentCount: "2877",
      },
    },
    {
      kind: "youtube#video",
      etag: "7M04l7TRaHASVP5XeOysk01sMbo",
      id: "m9EX0f6V11Y",
      snippet: {
        publishedAt: "2022-03-15T14:00:03Z",
        channelId: "UCvC4D8onUfXzvjTOM-dBfEA",
        title: "Marvel Studios’ Ms. Marvel | Official Trailer | Disney+",
        description:
          "The future is in her hands.\nMs. Marvel, an Original series from Marvel Studios, starts streaming June 8 on Disney+.  \n\n► Watch Marvel on Disney+: https://bit.ly/2XyBSIW\n► Subscribe to Marvel on YouTube: http://bit.ly/WeO3YJ\n\nFollow Marvel on Twitter: ‪https://twitter.com/marvel\nLike Marvel on Facebook: ‪https://www.facebook.com/marvel\nWatch Marvel on Twitch: https://www.twitch.tv/marvel\n\nReward your Marvel fandom by joining Marvel Insider!\nEarn points, then redeem for awesome rewards.\nTerms and conditions apply. \nLearn more at https://www.marvel.com/insider?Osocial=YT&CID=MarvelInsider\n\nFor even more news, stay tuned to:\nTumblr: ‪http://marvelentertainment.tumblr.com/\nInstagram: https://www.instagram.com/marvel\nPinterest: ‪http://pinterest.com/marvelofficial\nReddit: http://reddit.com/u/marvel-official",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/m9EX0f6V11Y/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/m9EX0f6V11Y/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/m9EX0f6V11Y/hqdefault.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "Marvel Entertainment",
        tags: [
          "marvel",
          "comics",
          "ms marvel",
          "msmarvel",
          "ms. marvel",
          "kamala khan",
          "ms marvel trailer",
          "ms. marvel trailer",
          "trailer",
          "teaser",
          "official trailer",
          "marvel studios",
          "disney+",
          "disneyplus",
          "disney plus",
        ],
        categoryId: "24",
        liveBroadcastContent: "none",
        localized: {
          title: "Marvel Studios’ Ms. Marvel | Official Trailer | Disney+",
          description:
            "The future is in her hands.\nMs. Marvel, an Original series from Marvel Studios, starts streaming June 8 on Disney+.  \n\n► Watch Marvel on Disney+: https://bit.ly/2XyBSIW\n► Subscribe to Marvel on YouTube: http://bit.ly/WeO3YJ\n\nFollow Marvel on Twitter: ‪https://twitter.com/marvel\nLike Marvel on Facebook: ‪https://www.facebook.com/marvel\nWatch Marvel on Twitch: https://www.twitch.tv/marvel\n\nReward your Marvel fandom by joining Marvel Insider!\nEarn points, then redeem for awesome rewards.\nTerms and conditions apply. \nLearn more at https://www.marvel.com/insider?Osocial=YT&CID=MarvelInsider\n\nFor even more news, stay tuned to:\nTumblr: ‪http://marvelentertainment.tumblr.com/\nInstagram: https://www.instagram.com/marvel\nPinterest: ‪http://pinterest.com/marvelofficial\nReddit: http://reddit.com/u/marvel-official",
        },
        defaultAudioLanguage: "en",
      },
      contentDetails: {
        duration: "PT1M48S",
        dimension: "2d",
        definition: "hd",
        caption: "true",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "12596123",
        likeCount: "614814",
        favoriteCount: "0",
        commentCount: "43021",
      },
    },
    {
      kind: "youtube#video",
      etag: "bqEUFjm4S09bI_nqiNEAsSiRAeU",
      id: "UgjL1seJ5Ak",
      snippet: {
        publishedAt: "2022-03-16T17:00:11Z",
        channelId: "UCvfat4DPrM3BM-xZ2zn5ruQ",
        title: "NoCap -Shackles to Diamonds (Official Video)",
        description:
          "NoCap - Shackle to Diamonds (Official Video)\n\nShackles to Diamond- Stream/Download: https://nocap.lnk.to/mrcrawford\n\nSubscribe for more official content from NoCap: \nhttps://nocap.lnk.to/YouTubeAY\n\nMr. Crawford Pre- Save : nocap.lnk.to/MrCrawford\n\n\nFollow NoCap:\nhttp://instagram.com/thebackendchild \nhttps://twitter.com/NoCap\nhttps://soundcloud.com/officialnocap\nhttps://www.facebook.com/NoCapOfficial",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/UgjL1seJ5Ak/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/UgjL1seJ5Ak/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/UgjL1seJ5Ak/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/UgjL1seJ5Ak/sddefault.jpg",
            width: 640,
            height: 480,
          },
        },
        channelTitle: "NoCap",
        tags: [
          "nocap",
          "thebackendchild",
          "ghetto angels",
          "legend",
          "point guard",
          "rylo rodriguez",
          "rylo",
          "free ghetto",
          "blind nights",
          "freestyle",
          "mobile",
          "alabama",
          "innocent",
          "nba youngboy",
          "quando rondo",
          "evol",
          "exotic",
          "lyrics",
          "rap lyrics",
          "official",
          "official video",
          "official audio",
        ],
        categoryId: "10",
        liveBroadcastContent: "none",
        localized: {
          title: "NoCap -Shackles to Diamonds (Official Video)",
          description:
            "NoCap - Shackle to Diamonds (Official Video)\n\nShackles to Diamond- Stream/Download: https://nocap.lnk.to/mrcrawford\n\nSubscribe for more official content from NoCap: \nhttps://nocap.lnk.to/YouTubeAY\n\nMr. Crawford Pre- Save : nocap.lnk.to/MrCrawford\n\n\nFollow NoCap:\nhttp://instagram.com/thebackendchild \nhttps://twitter.com/NoCap\nhttps://soundcloud.com/officialnocap\nhttps://www.facebook.com/NoCapOfficial",
        },
        defaultAudioLanguage: "en",
      },
      contentDetails: {
        duration: "PT2M45S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "281168",
        likeCount: "25658",
        favoriteCount: "0",
        commentCount: "1173",
      },
    },
    {
      kind: "youtube#video",
      etag: "fV-addUjVV-2xM9_H7rZnR7F5OU",
      id: "BDnldThOAhw",
      snippet: {
        publishedAt: "2022-03-16T18:03:41Z",
        channelId: "UCUs8sGiP4avNaYNVO22INhQ",
        title:
          "Machine Gun Kelly – maybe ft. Bring Me The Horizon (Official Visualizer)",
        description:
          'Machine Gun Kelly "maybe ft. Bring Me The Horizon" available now: https://MGK.lnk.to/maybe\n \nPre-order \'mainstream sellout\' featuring “maybe ft. Bring Me The Horizon,” “ay! Ft. Lil Wayne,” "papercuts," and "emo girl ft. WILLOW" before it’s released March 25: https://mgk.lnk.to/mainstreamsellout\n \n\'mainstream sellout\' box sets available for pre-order today: http://store.machinegunkelly.com\n \nFollow @Machine Gun Kelly:\nhttps://tiktok.com/@machinegunkelly\nhttp://twitter.com/machinegunkelly\nhttp://instagram.com/machinegunkelly\nhttp://facebook.com/machinegunkelly\nhttp://machinegunkelly.com\n \nFollow @Bring Me The Horizon: \nhttps://instagram.com/bringmethehorizon\nhttps://twitter.com/bmthofficial\nhttps://facebook.com/bmthofficial\nhttps://youtube.com/user/BMTHchannel\nhttps://www.tiktok.com/@officialbmth  \nhttp://bmthorizon.co/newsletter           \nhttps://bmth.co/listen\n \nPhotos: Jordi Koalitic | https://instagram.com/jordi.koalitic\nVideo Editing: Visual Frisson | https://instagram.com/visualfrisson/\n\nLyrics:\n2,3,5!\n \nMaybe If I had something to say\nButterfly effect from the last three days now\nMaybe if I had something to save\nI used to have a soul until I threw it away\nThere’s shadows on the wall, wish I would’ve ran\nGotta get away I hope you understand\nI try to hide my face like a wanted man \nMaybe I’ll be gone before you count to 10\n \nI made up my mind this evening\nI’m taking the last I’m taking the last\nDrink while my conscious eats me \nI’m taking the last I’m taking the last\nI’m ready to let you go\nI’m ready to let you go\nI’m ready to let you go\nThis time is the last this time is the last\n \nMaybe if we went another way\nI wouldn’t be regretting the decisions that I made\nI don’t want to spend another day\nLooking for somebody that I know I can’t replace\nMy tears fall you don’t miss me\nPut me out my misery\nThink my heart is history \nI think I’m broke and nothing can fix me\n \nI made up my mind this evening\nI’m taking the last I’m taking the last\nDrink while my conscious eats me \nI’m taking the last I’m taking the last\nI’m ready to let you go\nI’m ready to let you go\nI’m ready to let you go\nThis time is the last this time is the last\n \nYeah\nWe were built to fall apart\nBut I can’t feel you now\nAnd it’s too late now there’s no point screaming\nDug your grave so fuck your feelings\nNo one’s here so now you’re on your own\n \nI made up my mind this evening\nI’m taking the last I’m taking the last\nDrink while my conscious eats me \nI’m taking the last I’m taking the last\nI’m ready to let you go\nI’m ready to let you go\nI’m ready to let you go\nThis time is the last this time is the last\nI’m ready to let you go\nI’m ready to let you go\nI’m ready to let you go\nThis time is the last this time is the last\n \n#MGK #BMTH #MAYBE',
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/BDnldThOAhw/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/BDnldThOAhw/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/BDnldThOAhw/hqdefault.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "Machine Gun Kelly",
        tags: [
          "machine gun kelly",
          "mainstream sellout",
          "bring me the horizion",
          "maybe",
          "MGK",
          "Oli",
          "Oliver Sykes",
          "oli skyes",
          "emo gil",
          "ay!",
          "papercuts",
          "Colson baker",
          "new mgk",
          "BMTH",
          "MGK x BMTH",
          "mgk and bring me the horizon",
        ],
        categoryId: "10",
        liveBroadcastContent: "none",
        localized: {
          title:
            "Machine Gun Kelly – maybe ft. Bring Me The Horizon (Official Visualizer)",
          description:
            'Machine Gun Kelly "maybe ft. Bring Me The Horizon" available now: https://MGK.lnk.to/maybe\n \nPre-order \'mainstream sellout\' featuring “maybe ft. Bring Me The Horizon,” “ay! Ft. Lil Wayne,” "papercuts," and "emo girl ft. WILLOW" before it’s released March 25: https://mgk.lnk.to/mainstreamsellout\n \n\'mainstream sellout\' box sets available for pre-order today: http://store.machinegunkelly.com\n \nFollow @Machine Gun Kelly:\nhttps://tiktok.com/@machinegunkelly\nhttp://twitter.com/machinegunkelly\nhttp://instagram.com/machinegunkelly\nhttp://facebook.com/machinegunkelly\nhttp://machinegunkelly.com\n \nFollow @Bring Me The Horizon: \nhttps://instagram.com/bringmethehorizon\nhttps://twitter.com/bmthofficial\nhttps://facebook.com/bmthofficial\nhttps://youtube.com/user/BMTHchannel\nhttps://www.tiktok.com/@officialbmth  \nhttp://bmthorizon.co/newsletter           \nhttps://bmth.co/listen\n \nPhotos: Jordi Koalitic | https://instagram.com/jordi.koalitic\nVideo Editing: Visual Frisson | https://instagram.com/visualfrisson/\n\nLyrics:\n2,3,5!\n \nMaybe If I had something to say\nButterfly effect from the last three days now\nMaybe if I had something to save\nI used to have a soul until I threw it away\nThere’s shadows on the wall, wish I would’ve ran\nGotta get away I hope you understand\nI try to hide my face like a wanted man \nMaybe I’ll be gone before you count to 10\n \nI made up my mind this evening\nI’m taking the last I’m taking the last\nDrink while my conscious eats me \nI’m taking the last I’m taking the last\nI’m ready to let you go\nI’m ready to let you go\nI’m ready to let you go\nThis time is the last this time is the last\n \nMaybe if we went another way\nI wouldn’t be regretting the decisions that I made\nI don’t want to spend another day\nLooking for somebody that I know I can’t replace\nMy tears fall you don’t miss me\nPut me out my misery\nThink my heart is history \nI think I’m broke and nothing can fix me\n \nI made up my mind this evening\nI’m taking the last I’m taking the last\nDrink while my conscious eats me \nI’m taking the last I’m taking the last\nI’m ready to let you go\nI’m ready to let you go\nI’m ready to let you go\nThis time is the last this time is the last\n \nYeah\nWe were built to fall apart\nBut I can’t feel you now\nAnd it’s too late now there’s no point screaming\nDug your grave so fuck your feelings\nNo one’s here so now you’re on your own\n \nI made up my mind this evening\nI’m taking the last I’m taking the last\nDrink while my conscious eats me \nI’m taking the last I’m taking the last\nI’m ready to let you go\nI’m ready to let you go\nI’m ready to let you go\nThis time is the last this time is the last\nI’m ready to let you go\nI’m ready to let you go\nI’m ready to let you go\nThis time is the last this time is the last\n \n#MGK #BMTH #MAYBE',
        },
      },
      contentDetails: {
        duration: "PT2M50S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: false,
        regionRestriction: {
          blocked: ["BY", "RU"],
        },
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "928493",
        likeCount: "62743",
        favoriteCount: "0",
        commentCount: "4403",
      },
    },
    {
      kind: "youtube#video",
      etag: "YKjPaEQa8wmUo0W1VwBuBAkoG7E",
      id: "IcEqRYpbSN8",
      snippet: {
        publishedAt: "2022-03-16T04:06:10Z",
        channelId: "UCdqp0KK_Io7TwK5cJMBvB0Q",
        title: "Crushing my cameramans truck and giving him a new one",
        description:
          "Backing over my cameramans extremely sentimental Toyota with my excavator and giving him a brand new 2021 tacoma.",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/IcEqRYpbSN8/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/IcEqRYpbSN8/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/IcEqRYpbSN8/hqdefault.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "WhistlinDiesel",
        tags: [
          "Cameraman",
          "Destroy",
          "Crush",
          "Excavator",
          "Equipment",
          "WhistlinDiesel",
          "Off-road",
          "Diesel",
          "Trucks",
          "Bulldozer",
          "Cat",
          "Caterpillar",
          "Toyota",
          "Hilux",
          "Tacoma",
        ],
        categoryId: "22",
        liveBroadcastContent: "none",
        localized: {
          title: "Crushing my cameramans truck and giving him a new one",
          description:
            "Backing over my cameramans extremely sentimental Toyota with my excavator and giving him a brand new 2021 tacoma.",
        },
      },
      contentDetails: {
        duration: "PT11M19S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "1298713",
        likeCount: "72916",
        favoriteCount: "0",
        commentCount: "4169",
      },
    },
    {
      kind: "youtube#video",
      etag: "63tF4L8XbzffL3SOfLG-SUvegi0",
      id: "NBgEBWT1Mqk",
      snippet: {
        publishedAt: "2022-03-14T20:48:18Z",
        channelId: "UClW4jraMKz6Qj69lJf-tODA",
        title: "NBA YoungBoy - I Got The Bag",
        description:
          "YoungBoy Never Broke Again –  \n‘Sincerely, Kentrell’ OUT NOW: https://youngboy.lnk.to/SincerelyKentrellID\n \nSubscribe for more official content from YoungBoy NBA: \nhttps://youngboy.lnk.to/Subscribe\n \nConnect with YoungBoy Never Broke Again: \nhttp://www.youngboynba.com\nhttps://www.facebook.com/nbayoungboy\nhttps://www.twitter.com/GGYOUNGBOY\nhttps://www.instagram.com/nba_youngboy\nhttps://www.soundcloud.com/nba-youngboy\n \nThe official YouTube channel of Atlantic Records artist YoungBoy Never Broke Again. Subscribe for the latest music videos, performances, and more. \n\n#YoungBoyNeverBrokeAgain #SincerelyKentrell #",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/NBgEBWT1Mqk/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/NBgEBWT1Mqk/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/NBgEBWT1Mqk/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/NBgEBWT1Mqk/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/NBgEBWT1Mqk/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "YoungBoy Never Broke Again",
        tags: [
          "YoungBoy Never Broke Again",
          "NBA YoungBoy",
          "YoungBoy Quando Rondo",
          "YoungBoy Leak",
          "Make No Sense YoungBoy",
          "Youngboy Lost Motives",
          "YoungBoy NBA Music Video",
          "YoungBoy Never Broke Again TOP",
          "nba youngboy top",
          "YoungBoy NBA TOP album",
          "7KTt4_M09Rw",
          "0C80BSgjb8M",
          "qChxuVxs8FA",
          "dYk-yCsuTUo",
          "6MCSr65d9Xc",
          "ALimx-H8C6s",
          "YoungBoy Never Broke Again Sincerely Kentrell",
          "Sincerely Kentrell",
          "Youngboy NBA Sincerely Kentrell",
          "Sincerely Kentrell album",
          "YBNBA Sincerely Kentrell",
          "YB Sincerely Kentrell",
          "Kentrell",
        ],
        categoryId: "10",
        liveBroadcastContent: "none",
        localized: {
          title: "NBA YoungBoy - I Got The Bag",
          description:
            "YoungBoy Never Broke Again –  \n‘Sincerely, Kentrell’ OUT NOW: https://youngboy.lnk.to/SincerelyKentrellID\n \nSubscribe for more official content from YoungBoy NBA: \nhttps://youngboy.lnk.to/Subscribe\n \nConnect with YoungBoy Never Broke Again: \nhttp://www.youngboynba.com\nhttps://www.facebook.com/nbayoungboy\nhttps://www.twitter.com/GGYOUNGBOY\nhttps://www.instagram.com/nba_youngboy\nhttps://www.soundcloud.com/nba-youngboy\n \nThe official YouTube channel of Atlantic Records artist YoungBoy Never Broke Again. Subscribe for the latest music videos, performances, and more. \n\n#YoungBoyNeverBrokeAgain #SincerelyKentrell #",
        },
      },
      contentDetails: {
        duration: "PT2M22S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "4109820",
        likeCount: "261805",
        favoriteCount: "0",
        commentCount: "23250",
      },
    },
    {
      kind: "youtube#video",
      etag: "T6cKLm8KQhFI4qjJPQrdJ6htOmk",
      id: "1_OVqnSg8eA",
      snippet: {
        publishedAt: "2022-03-15T22:28:42Z",
        channelId: "UCK7mk2tt1FtBs5VqocHQtzg",
        title: "how i messed everything up #shorts",
        description: "",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/1_OVqnSg8eA/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/1_OVqnSg8eA/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/1_OVqnSg8eA/hqdefault.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "Alex Griswold",
        categoryId: "24",
        liveBroadcastContent: "none",
        localized: {
          title: "how i messed everything up #shorts",
          description: "",
        },
      },
      contentDetails: {
        duration: "PT22S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: false,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "1716479",
        likeCount: "118937",
        favoriteCount: "0",
        commentCount: "685",
      },
    },
    {
      kind: "youtube#video",
      etag: "-YguH-kZRSPyz0NcMe4zGWBwefY",
      id: "_6YCNd3ONUU",
      snippet: {
        publishedAt: "2022-03-16T16:00:09Z",
        channelId: "UCy2bCk5KnIfjmWYFHMZcd5w",
        title: "ROSALÍA - HENTAI (Official Video)",
        description:
          "Official video for “HENTAI” by ROSALÍA \n\nListen & Download “HENTAI” out now: https://rosalia.lnk.to/HENTAI\nPre-Save ‘MOTOMAMI’: https://motomami.rosalia.com/\n \nDirected by Mitch Ryan\n \n\nLYRICS\n\nPa’ pero mírate   \nNo pienses más\nNa’ que pensar\nTan rico no puede ser\nDe cuero na’\nPero estoy encuerá’\n \nTe quiero ride\nComo a mi bike\nHazme un tape\nModo Spike\n \nYo la batí\nHasta que se montó\nLo segundo es chingarte\nLo primero es Dios\n \nSo, so, so, so, so, so good\nGood, good, so, so, so good\nSo, so, so good, so, so, so good\nSo good, hmm, so good\n \n \nEnamorada de tu pistola\nRoja amapola\nCrash esa ola\nCasi me controla\n \nEnamorada de tu pistola\nRoja amapola\nCrash esa ola\nCasi me controla\n \nTe quiero ride\nComo a mi bike\nHazme un tape\nModo Spike\n \nCaro como que tiene\nUn diamante en la punta\nSiempre me pone\nPor delante de esas putas\n \nSo, so, so, so, so, so good\nGood, good, so, so, so good\nSo, so, so good, so, so, so good\nSo good, hmm\n \nBebé, te quiero comer ya, ya\nYa te quiero hacer hentai\nYa te quiero hacer hentai\nYa te quiero hacer hentai\nHacerte hentai\nHmm, hentai\n \nAmazon Music - https://rosalia.lnk.to/HENTAI/amazonmusic\nApple Music - https://rosalia.lnk.to/HENTAI/applemusic\nAudiomack - https://rosalia.lnk.to/HENTAI/audiomack\nDeezer - https://rosalia.lnk.to/HENTAI/deezer\niTunes - https://rosalia.lnk.to/HENTAI/itunes\nSoundCloud - https://rosalia.lnk.to/HENTAI/soundcloud\nSpotify - https://rosalia.lnk.to/HENTAI/spotify\nTidal - https://rosalia.lnk.to/HENTAI/tidal\nYouTube Music - https://rosalia.lnk.to/HENTAI/youtubemusic\n \nFollow ROSALÍA \nFacebook - https://www.facebook.com/rosalia.vt\nInstagram - https://www.instagram.com/rosalia.vt/\nTwitter - https://twitter.com/rosalia\nTikTok - https://www.tiktok.com/@rosalia\n \nhttps://www.rosalia.com/\n \n#ROSALÍA #HENTAI #MOTOMAMI",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/_6YCNd3ONUU/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/_6YCNd3ONUU/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/_6YCNd3ONUU/hqdefault.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "RosaliaVEVO",
        tags: ["Columbia", "HENTAI", "Latin Pop", "ROSALÍA"],
        categoryId: "10",
        liveBroadcastContent: "none",
        localized: {
          title: "ROSALÍA - HENTAI (Official Video)",
          description:
            "Official video for “HENTAI” by ROSALÍA \n\nListen & Download “HENTAI” out now: https://rosalia.lnk.to/HENTAI\nPre-Save ‘MOTOMAMI’: https://motomami.rosalia.com/\n \nDirected by Mitch Ryan\n \n\nLYRICS\n\nPa’ pero mírate   \nNo pienses más\nNa’ que pensar\nTan rico no puede ser\nDe cuero na’\nPero estoy encuerá’\n \nTe quiero ride\nComo a mi bike\nHazme un tape\nModo Spike\n \nYo la batí\nHasta que se montó\nLo segundo es chingarte\nLo primero es Dios\n \nSo, so, so, so, so, so good\nGood, good, so, so, so good\nSo, so, so good, so, so, so good\nSo good, hmm, so good\n \n \nEnamorada de tu pistola\nRoja amapola\nCrash esa ola\nCasi me controla\n \nEnamorada de tu pistola\nRoja amapola\nCrash esa ola\nCasi me controla\n \nTe quiero ride\nComo a mi bike\nHazme un tape\nModo Spike\n \nCaro como que tiene\nUn diamante en la punta\nSiempre me pone\nPor delante de esas putas\n \nSo, so, so, so, so, so good\nGood, good, so, so, so good\nSo, so, so good, so, so, so good\nSo good, hmm\n \nBebé, te quiero comer ya, ya\nYa te quiero hacer hentai\nYa te quiero hacer hentai\nYa te quiero hacer hentai\nHacerte hentai\nHmm, hentai\n \nAmazon Music - https://rosalia.lnk.to/HENTAI/amazonmusic\nApple Music - https://rosalia.lnk.to/HENTAI/applemusic\nAudiomack - https://rosalia.lnk.to/HENTAI/audiomack\nDeezer - https://rosalia.lnk.to/HENTAI/deezer\niTunes - https://rosalia.lnk.to/HENTAI/itunes\nSoundCloud - https://rosalia.lnk.to/HENTAI/soundcloud\nSpotify - https://rosalia.lnk.to/HENTAI/spotify\nTidal - https://rosalia.lnk.to/HENTAI/tidal\nYouTube Music - https://rosalia.lnk.to/HENTAI/youtubemusic\n \nFollow ROSALÍA \nFacebook - https://www.facebook.com/rosalia.vt\nInstagram - https://www.instagram.com/rosalia.vt/\nTwitter - https://twitter.com/rosalia\nTikTok - https://www.tiktok.com/@rosalia\n \nhttps://www.rosalia.com/\n \n#ROSALÍA #HENTAI #MOTOMAMI",
        },
      },
      contentDetails: {
        duration: "PT2M54S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        regionRestriction: {
          blocked: ["RU"],
        },
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "1438669",
        likeCount: "118993",
        favoriteCount: "0",
        commentCount: "9178",
      },
    },
    {
      kind: "youtube#video",
      etag: "tL1Hk7P1wfLE_3AmhTf-aCbw4_Q",
      id: "QquG9a8xpfk",
      snippet: {
        publishedAt: "2022-03-15T19:00:21Z",
        channelId: "UCl22N0AB65gzuFpDQu2O6-g",
        title:
          "#vegan is fun lol #bbq #food #lifehack #steak #garlic #vegetarian #viral #satisfying #cook #shorts",
        description: "",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/QquG9a8xpfk/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/QquG9a8xpfk/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/QquG9a8xpfk/hqdefault.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "Mark Chrispy",
        categoryId: "23",
        liveBroadcastContent: "none",
        localized: {
          title:
            "#vegan is fun lol #bbq #food #lifehack #steak #garlic #vegetarian #viral #satisfying #cook #shorts",
          description: "",
        },
      },
      contentDetails: {
        duration: "PT18S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: false,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "2091175",
        likeCount: "106548",
        favoriteCount: "0",
        commentCount: "557",
      },
    },
    {
      kind: "youtube#video",
      etag: "tNbCwOzQiJ574SRH7TsQkp5xGlY",
      id: "oOWlz6vqsuw",
      snippet: {
        publishedAt: "2022-03-15T20:09:47Z",
        channelId: "UC0ufW3qv1DDE8ucnwK6jvTA",
        title: "Dogs Meet Our New Baby for First Time",
        description:
          "We bring home our new baby and introduce them to our dogs. Will they be good brothers or is this a bad idea?  Please have the cutest reaction!!! Will Matt and Rebecca Zamolo be able to handle this? \n\nOther Amazing Videos\n\nCute Babies and Pets TV - ♥Cute Puppies Doing Funny Things 2020♥ #3 Cutest Dogs https://www.youtube.com/watch?v=fBYvHHT8fdE\n\nHidden GoPro Camera Reveals our Dogs Opening Christmas Presents Early! | Spying for 24 hours! - https://www.youtube.com/watch?v=uAQS95Mpzw8\n\nHidden Camera Catches our Dogs With Creepy Doll! Spying for 24 hours! - https://www.youtube.com/watch?v=oE5cB8YHV2Y\n\nTucker Budzyn - My Dog Reacts to the Toilet Paper Challenge https://www.youtube.com/watch?v=0YCW691BL9k",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/oOWlz6vqsuw/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/oOWlz6vqsuw/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/oOWlz6vqsuw/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/oOWlz6vqsuw/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/oOWlz6vqsuw/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "PawZam Dogs",
        tags: ["dogs", "meet", "our", "new", "baby", "first", "time"],
        categoryId: "15",
        liveBroadcastContent: "none",
        defaultLanguage: "en",
        localized: {
          title: "Dogs Meet Our New Baby for First Time",
          description:
            "We bring home our new baby and introduce them to our dogs. Will they be good brothers or is this a bad idea?  Please have the cutest reaction!!! Will Matt and Rebecca Zamolo be able to handle this? \n\nOther Amazing Videos\n\nCute Babies and Pets TV - ♥Cute Puppies Doing Funny Things 2020♥ #3 Cutest Dogs https://www.youtube.com/watch?v=fBYvHHT8fdE\n\nHidden GoPro Camera Reveals our Dogs Opening Christmas Presents Early! | Spying for 24 hours! - https://www.youtube.com/watch?v=uAQS95Mpzw8\n\nHidden Camera Catches our Dogs With Creepy Doll! Spying for 24 hours! - https://www.youtube.com/watch?v=oE5cB8YHV2Y\n\nTucker Budzyn - My Dog Reacts to the Toilet Paper Challenge https://www.youtube.com/watch?v=0YCW691BL9k",
        },
        defaultAudioLanguage: "en",
      },
      contentDetails: {
        duration: "PT8M26S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "1387032",
        likeCount: "25611",
        favoriteCount: "0",
        commentCount: "3572",
      },
    },
    {
      kind: "youtube#video",
      etag: "CTb_bE8MSNTOAX6zPPr4wIIBxec",
      id: "ia6fRSeK8I0",
      snippet: {
        publishedAt: "2022-03-15T03:21:02Z",
        channelId: "UCuIpkP1H2Vb_NFu8dLIWoPw",
        title: "jai shree ram 🚩#shorts #ashortaday",
        description: "",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/ia6fRSeK8I0/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/ia6fRSeK8I0/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/ia6fRSeK8I0/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/ia6fRSeK8I0/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/ia6fRSeK8I0/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "CHANDAN ART ACADEMY",
        categoryId: "27",
        liveBroadcastContent: "none",
        localized: {
          title: "jai shree ram 🚩#shorts #ashortaday",
          description: "",
        },
        defaultAudioLanguage: "hi",
      },
      contentDetails: {
        duration: "PT15S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: false,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "93665745",
        likeCount: "5005975",
        favoriteCount: "0",
        commentCount: "35104",
      },
    },
    {
      kind: "youtube#video",
      etag: "9PhQeJVndZyONicHU8yQNqR_O4U",
      id: "mQf1IxxZGCI",
      snippet: {
        publishedAt: "2022-03-14T23:00:23Z",
        channelId: "UCaxOQZrF5llUMp-JjesUz1A",
        title: "Lil Durk - Barbarian (Official Video)",
        description:
          '7220, the new album from Lil Durk. Available now:\nhttps://lildurk.lnk.to/7220\n\nListen to "Barbarian", available now:\nhttps://lildurk.lnk.to/7220\n\nMerch: https://otfgear.com/\n\nFollow Lil Durk:\nInstagram - https://instagram.com/lildurk\nTwitter - https://twitter.com/lildurk\nTikTok - https://www.tiktok.com/@lildurk\nFacebook - https://fb.com/lildurk\nGiphy - https://lildurk.lnk.to/Giphy\n\nListen to Lil Durk:\nApple Music: https://lildurk.lnk.to/applemusic\nSpotify: https://lildurk.lnk.to/spotify\nSoundCloud - https://lildurk.lnk.to/soundcloud\n\nSubscribe: http://lildurk.lnk.to/YouTube\n\nShot by @JerryPHD\n\n#LilDurk #7220 #Barbarian',
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/mQf1IxxZGCI/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/mQf1IxxZGCI/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/mQf1IxxZGCI/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/mQf1IxxZGCI/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/mQf1IxxZGCI/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Lil Durk",
        tags: [
          "lil durk",
          "lil durk music",
          "lil durk music video",
          "just cause yall waited 2",
          "lil durk 2020",
          "just cause y'all waited 2",
          "durkio",
          "smurkio",
          "lil durk official",
          "drill",
          "drill music",
          "chicago hip hop",
          "only the family",
          "OTF",
        ],
        categoryId: "10",
        liveBroadcastContent: "none",
        localized: {
          title: "Lil Durk - Barbarian (Official Video)",
          description:
            '7220, the new album from Lil Durk. Available now:\nhttps://lildurk.lnk.to/7220\n\nListen to "Barbarian", available now:\nhttps://lildurk.lnk.to/7220\n\nMerch: https://otfgear.com/\n\nFollow Lil Durk:\nInstagram - https://instagram.com/lildurk\nTwitter - https://twitter.com/lildurk\nTikTok - https://www.tiktok.com/@lildurk\nFacebook - https://fb.com/lildurk\nGiphy - https://lildurk.lnk.to/Giphy\n\nListen to Lil Durk:\nApple Music: https://lildurk.lnk.to/applemusic\nSpotify: https://lildurk.lnk.to/spotify\nSoundCloud - https://lildurk.lnk.to/soundcloud\n\nSubscribe: http://lildurk.lnk.to/YouTube\n\nShot by @JerryPHD\n\n#LilDurk #7220 #Barbarian',
        },
        defaultAudioLanguage: "en",
      },
      contentDetails: {
        duration: "PT2M35S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        regionRestriction: {
          blocked: ["RU"],
        },
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "2563842",
        likeCount: "109374",
        favoriteCount: "0",
        commentCount: "6727",
      },
    },
    {
      kind: "youtube#video",
      etag: "zdZH85t9LjjNC5AfbjPQD-Ycidg",
      id: "KP1BrX1pDrg",
      snippet: {
        publishedAt: "2022-03-15T18:00:10Z",
        channelId: "UCFlC8U0Uif2hF0FIgsSIIYQ",
        title:
          "Grupo Firme - Beto Sierra - Mc Davo - Asi Es La Vida - (Official Video)",
        description:
          "by Grupo Firme performing - Asi Es La Vida -. © 2022 Isael Gutierrez & Evert Gutierrez , Exclusive License To Music Vip Entertainment \nSuscribete Aqui https://bit.ly/333fXen\n\nDirector: Isael Gutierrez & Evert Gutierrez \nTema: Asi Es La Vida\nAutor: Alberto Sierra, Emmanuel Delgado, David Sierra\nDirector De Fotografia : Daniel Nice\nDuración: 3:21\nDisquera: Music VIP Entertainment  ℗ 2022\nGénero: Regional Mexicano \nEditora:Music VIP Entertainment.\n\nProvided to YouTube by  Music VIP Entertainment Inc. ℗ 2022\nReleased on: 2022-03-14 Auto-generated by YouTube.\n#MUSICVIP",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/KP1BrX1pDrg/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/KP1BrX1pDrg/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/KP1BrX1pDrg/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/KP1BrX1pDrg/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/KP1BrX1pDrg/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Grupo Firme",
        tags: [
          "Grupo Firme",
          "Firme",
          "MC Davo",
          "Beto Sierra",
          "Grupo Firme nuevo video",
          "Grupo Firme video",
          "Grupo Firme video oficial",
          "Grupo Firme mix 2022",
          "Grupo Firme new video",
          "Grupo Firme official video",
          "Grupo Firme video nuevo",
          "MC Davo music",
          "MC Davo nuevo video",
          "MC Davo video",
          "MC Davo video oficial",
          "MC Davo mix 2022",
          "MC Davo new video",
          "MC Davo official video",
          "MC Davo video nuevo",
          "new single MC Davo",
          "Firme music",
          "asi es la vida",
          "mexico",
          "eduin",
          "eduin caz",
          "grupo firme mix",
        ],
        categoryId: "10",
        liveBroadcastContent: "none",
        defaultLanguage: "es-MX",
        localized: {
          title:
            "Grupo Firme - Beto Sierra - Mc Davo - Asi Es La Vida - (Official Video)",
          description:
            "by Grupo Firme performing - Asi Es La Vida -. © 2022 Isael Gutierrez & Evert Gutierrez , Exclusive License To Music Vip Entertainment \nSuscribete Aqui https://bit.ly/333fXen\n\nDirector: Isael Gutierrez & Evert Gutierrez \nTema: Asi Es La Vida\nAutor: Alberto Sierra, Emmanuel Delgado, David Sierra\nDirector De Fotografia : Daniel Nice\nDuración: 3:21\nDisquera: Music VIP Entertainment  ℗ 2022\nGénero: Regional Mexicano \nEditora:Music VIP Entertainment.\n\nProvided to YouTube by  Music VIP Entertainment Inc. ℗ 2022\nReleased on: 2022-03-14 Auto-generated by YouTube.\n#MUSICVIP",
        },
        defaultAudioLanguage: "es-MX",
      },
      contentDetails: {
        duration: "PT3M",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "1960286",
        likeCount: "109141",
        favoriteCount: "0",
        commentCount: "5394",
      },
    },
    {
      kind: "youtube#video",
      etag: "BpjHroL6ft--tjS9gUzcmDyskP8",
      id: "TEpfarXxO7o",
      snippet: {
        publishedAt: "2022-03-16T16:00:12Z",
        channelId: "UCvJJ_dzjViJCoLf5uKUTwoA",
        title: "Why The U.S. Is Running Out Of Everything",
        description:
          "The United States is experiencing a shortage in rubber, sand and people. Rubber is a critical raw material needed for car tires, personal protective equipment such as masks and gloves, and many more everyday products. Anytime you’re going anywhere, you’re using rubber. Now, supply chain disruptions have thrown the rubber industry into a tailspin. The global rubber market was valued at nearly $40 billion in 2020, but one analysis predicts the natural rubber market could be worth nearly $68.5 billion by 2026. Rubber producers are facing climate change, the Covid-19 pandemic, a destructive fungus and the fight for shipping containers. “We could be on the cusp of a rubber apocalypse,” Ohio State University professor Katrina Cornish told CNBC.\n\nEven though sand can be found in nearly every single country on Earth, the world could soon face a shortage of this crucial, under-appreciated commodity. In the last twenty years, sand use around the world has tripled, according to the UNEP. That’s far greater than the rate at which sand is being replenished.\n\nAdditionally, the U.S. is facing an aging population, falling birth rate and economic recession caused by the Covid-19 pandemic. These issues will have huge implications on the size of the workforce and the consumer base.\n\nSEGMENTS:\n00:00 What The Rubber ‘Apocalypse’ Means For The U.S. Economy\n11:18 Why The World Is Running Out Of Sand\n21:11 Is The U.S. Running Out Of People?\n\n» Subscribe to CNBC: https://cnb.cx/SubscribeCNBC\n» Subscribe to CNBC TV: https://cnb.cx/SubscribeCNBCtelevision\n» Subscribe to CNBC Classic: https://cnb.cx/SubscribeCNBCclassic\n\nAbout CNBC: From 'Wall Street' to 'Main Street' to award winning original documentaries and Reality TV series, CNBC has you covered. Experience special sneak peeks of your favorite shows, exclusive video and more.\n\nConnect with CNBC News Online\nGet the latest news: https://www.cnbc.com/\nFollow CNBC on LinkedIn: https://cnb.cx/LinkedInCNBC\nFollow CNBC News on Facebook: https://cnb.cx/LikeCNBC\nFollow CNBC News on Twitter: https://cnb.cx/FollowCNBC\nFollow CNBC News on Instagram: https://cnb.cx/InstagramCNBC\nSubscribe to CNBC PRO: https://cnb.cx/2NLi9AN\n\nWhat The Rubber ‘Apocalypse’ Means For The U.S. Economy\n\n#CNBC\n\nWhy The U.S. Is Running Out Of Everything",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/TEpfarXxO7o/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/TEpfarXxO7o/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/TEpfarXxO7o/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/TEpfarXxO7o/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/TEpfarXxO7o/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "CNBC",
        tags: [
          "cnbc",
          "news",
          "financial news",
          "business news",
          "rubber",
          "economy",
          "us economy",
          "usa",
          "stocks",
          "stock market",
          "investing",
          "investments",
          "tires",
          "rubber shortage",
          "shortages",
          "shipping",
          "imports",
          "trade",
          "breaking news",
          "CNBC",
          "business",
          "finance stock",
          "news channel",
          "news station",
          "us news",
          "world news",
          "cable news",
          "finance news",
          "money",
          "money tips",
          "Stock market news",
          "construction",
          "sand shortage",
          "population",
        ],
        categoryId: "25",
        liveBroadcastContent: "none",
        localized: {
          title: "Why The U.S. Is Running Out Of Everything",
          description:
            "The United States is experiencing a shortage in rubber, sand and people. Rubber is a critical raw material needed for car tires, personal protective equipment such as masks and gloves, and many more everyday products. Anytime you’re going anywhere, you’re using rubber. Now, supply chain disruptions have thrown the rubber industry into a tailspin. The global rubber market was valued at nearly $40 billion in 2020, but one analysis predicts the natural rubber market could be worth nearly $68.5 billion by 2026. Rubber producers are facing climate change, the Covid-19 pandemic, a destructive fungus and the fight for shipping containers. “We could be on the cusp of a rubber apocalypse,” Ohio State University professor Katrina Cornish told CNBC.\n\nEven though sand can be found in nearly every single country on Earth, the world could soon face a shortage of this crucial, under-appreciated commodity. In the last twenty years, sand use around the world has tripled, according to the UNEP. That’s far greater than the rate at which sand is being replenished.\n\nAdditionally, the U.S. is facing an aging population, falling birth rate and economic recession caused by the Covid-19 pandemic. These issues will have huge implications on the size of the workforce and the consumer base.\n\nSEGMENTS:\n00:00 What The Rubber ‘Apocalypse’ Means For The U.S. Economy\n11:18 Why The World Is Running Out Of Sand\n21:11 Is The U.S. Running Out Of People?\n\n» Subscribe to CNBC: https://cnb.cx/SubscribeCNBC\n» Subscribe to CNBC TV: https://cnb.cx/SubscribeCNBCtelevision\n» Subscribe to CNBC Classic: https://cnb.cx/SubscribeCNBCclassic\n\nAbout CNBC: From 'Wall Street' to 'Main Street' to award winning original documentaries and Reality TV series, CNBC has you covered. Experience special sneak peeks of your favorite shows, exclusive video and more.\n\nConnect with CNBC News Online\nGet the latest news: https://www.cnbc.com/\nFollow CNBC on LinkedIn: https://cnb.cx/LinkedInCNBC\nFollow CNBC News on Facebook: https://cnb.cx/LikeCNBC\nFollow CNBC News on Twitter: https://cnb.cx/FollowCNBC\nFollow CNBC News on Instagram: https://cnb.cx/InstagramCNBC\nSubscribe to CNBC PRO: https://cnb.cx/2NLi9AN\n\nWhat The Rubber ‘Apocalypse’ Means For The U.S. Economy\n\n#CNBC\n\nWhy The U.S. Is Running Out Of Everything",
        },
        defaultAudioLanguage: "en",
      },
      contentDetails: {
        duration: "PT35M16S",
        dimension: "2d",
        definition: "hd",
        caption: "true",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "467829",
        likeCount: "5799",
        favoriteCount: "0",
        commentCount: "1937",
      },
    },
    {
      kind: "youtube#video",
      etag: "mS-US-Bsdmvro0txjR5qq3X7MTM",
      id: "xcmQr8Xit9E",
      snippet: {
        publishedAt: "2022-03-16T00:54:48Z",
        channelId: "UCYXykAzRUezpecj0yLKZsmA",
        title:
          "How to get parents to buy whatever you want🎮🔥 #shorts #viral #videogames #parents #prank #foryou",
        description: "",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/xcmQr8Xit9E/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/xcmQr8Xit9E/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/xcmQr8Xit9E/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/xcmQr8Xit9E/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/xcmQr8Xit9E/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "FamousReece",
        categoryId: "22",
        liveBroadcastContent: "none",
        localized: {
          title:
            "How to get parents to buy whatever you want🎮🔥 #shorts #viral #videogames #parents #prank #foryou",
          description: "",
        },
      },
      contentDetails: {
        duration: "PT20S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: false,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "621946",
        likeCount: "24172",
        favoriteCount: "0",
        commentCount: "437",
      },
    },
    {
      kind: "youtube#video",
      etag: "WdDabZ_aUE-XW0Boz7V5InOrzmY",
      id: "FbrTP754Bz8",
      snippet: {
        publishedAt: "2022-03-15T18:31:20Z",
        channelId: "UCXYuZE1DtlPBgz3-vSsKbfA",
        title: "Fortnite But It's Upside Down!",
        description:
          "I flipped the Fortnite map upside down and challenged my friends to find a hidden ball inside of it. After that, I hosted a bunch of more challenges and the person who completed the least amount of challenges had to do an embarrassing punishment!\n\nSUB TO THE BUILDERS IN THE VIDEO!\n\nKing: https://www.youtube.com/channel/UClQ-qZkosx6N-J2dy1lYVHg \nSven: https://www.youtube.com/c/SvenP\nFrog: https://www.youtube.com/JustAFrog \n\nSUBSCRIBE OR I'LL TAKE YOUR V BUCKS\n\nSay hi to me on these!:\nTwitter: https://twitter.com/LG_Melts\nInstagram: Bennett.Melt \nTwitch.TV/Meltards\nTik Tok: lgmelt\nMY DISCORD!: https://discord.com/invite/FUFdkK8\nCreator Code: Melts - ad\n\n#melt #fortnite #chapter3",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/FbrTP754Bz8/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/FbrTP754Bz8/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/FbrTP754Bz8/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/FbrTP754Bz8/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/FbrTP754Bz8/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Melt",
        tags: [
          "melt",
          "fortnite",
          "fortnite battle royale",
          "fortnite map flipped",
          "fortnite upside down",
          "fortnite map upside down",
          "upside down",
          "melt upside down",
          "lg melt",
          "lg melts",
          "fortnite melt",
          "fortnite chapter 3",
          "chapter 3",
          "fortnite but the maps upside down",
          "fortnite but its upside down",
          "fortnite but it's upside down",
          "melts",
        ],
        categoryId: "20",
        liveBroadcastContent: "none",
        localized: {
          title: "Fortnite But It's Upside Down!",
          description:
            "I flipped the Fortnite map upside down and challenged my friends to find a hidden ball inside of it. After that, I hosted a bunch of more challenges and the person who completed the least amount of challenges had to do an embarrassing punishment!\n\nSUB TO THE BUILDERS IN THE VIDEO!\n\nKing: https://www.youtube.com/channel/UClQ-qZkosx6N-J2dy1lYVHg \nSven: https://www.youtube.com/c/SvenP\nFrog: https://www.youtube.com/JustAFrog \n\nSUBSCRIBE OR I'LL TAKE YOUR V BUCKS\n\nSay hi to me on these!:\nTwitter: https://twitter.com/LG_Melts\nInstagram: Bennett.Melt \nTwitch.TV/Meltards\nTik Tok: lgmelt\nMY DISCORD!: https://discord.com/invite/FUFdkK8\nCreator Code: Melts - ad\n\n#melt #fortnite #chapter3",
        },
      },
      contentDetails: {
        duration: "PT15M55S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "656055",
        likeCount: "14028",
        favoriteCount: "0",
        commentCount: "913",
      },
    },
    {
      kind: "youtube#video",
      etag: "5hH0fGHFM6nX1rr0dVJYGvpH_YU",
      id: "L4KWhKY85cY",
      snippet: {
        publishedAt: "2022-03-14T20:00:04Z",
        channelId: "UCUaT_39o1x6qWjz7K2pWcgw",
        title: "Extreme Try Not To Laugh Challenge!",
        description:
          "Chris just won $10,000 BUT everytime he laughs, I spin a wheel where he could lose all his money!\n\nCHECK OUT THESE CHANNELS OR ELSE\nJifkin\nhttps://vm.tiktok.com/ZTdym3M3N/?k=1\n\nWilleezy Entertainment\nhttps://www.youtube.com/shorts/e0_bfc_1kCA\n\nLong-tax-77\nhttps://www.reddit.com/r/funnyvideos/comments/smtv72/bro_knows/\n\nPet.eles\nhttps://vm.tiktok.com/TTPdymG8xr/?k=1\n\nAuto_tuning_aksessuar\nhttps://www.instagram.com/reel/CYlYKGgMC8l/?utm_medium=copy_link\n\nSpace_walker24\nhttps://vm.tiktok.com/TTPdymbbdY/?k=1\n\nRound0range\nhttps://vm.tiktok.com/TTPdymTppU/?k=1\n\nSomewhiteguy690\nhttps://vm.tiktok.com/ZTdyupQRL/?k=1\n\nAwam..shuja\nhttps://vm.tiktok.com/ZTdymv1Ch/?k=1\n\nSpecere\nhttps://vm.tiktok.com/TTPdyuLWsc/?k=1\n\nFjerry\nhttps://vm.tiktok.com/TTPdyuLND5/?k=1\n\nKoresus\nhttps://vm.tiktok.com/ZTdymwyYM/?k=1\n\nKiddo480\nhttps://www.youtube.com/watch?v=9A1ZFSzXJ5U\n\nSammy Haig\nhttps://www.youtube.com/watch?v=COvju-gxCcw\n\nHanselsandovalr\nhttps://vm.tiktok.com/TTPdyuQMBw/?k=1\n\nTrippiedrob\nhttps://vm.tiktok.com/ZTdyua6NK/?k=1\n\nTheSyphon\nhttps://www.youtube.com/shorts/h5TeGqkw7MQ\n\nPreciseAnt76\nhttps://www.reddit.com/r/MemeVideos/comments/ss0t2r/can_you_lay_on_your_stomach/\n\n_sasuke\nhttps://www.reddit.com/r/MemeVideos/comments/qdc0tq/crip_walk/\n\nElforruso\nhttps://vm.tiktok.com/ZTdyuMojB/?k=1\n\nLstoast\nhttps://vm.tiktok.com/ZTdyuAWxV/?k=1\n\nVeysper\nhttps://vm.tiktok.com/ZTdyuQL1Y/?k=1\n\nDayyyumm_shorty\nhttps://vm.tiktok.com/TTPdyum4EF/?k=1\n\nOlejguy\nhttps://vm.tiktok.com/ZTdyumJJy/?k=1\n\nHoodshumor\nhttps://www.instagram.com/reel/CYm8Ah8F1qR/?utm_medium=copy_link\n\nJaysamuel1220\nhttps://www.youtube.com/watch?v=NoJTNebpk0I\n\n_Crotch_Goblin_\nhttps://www.reddit.com/r/dankvideos/comments/sjao3g/who_is_valve_guy_the_answer_was_right_infront_of/\n\nMikeymaybeme\nhttps://vm.tiktok.com/TTPdrmosGE/\n\nCarliejayes\nhttps://vm.tiktok.com/ZTdyucNNd/?k=1\n\nJamesmakesmusic\nhttps://vm.tiktok.com/ZTdyub1Gw/?k=1\n\nSmm_govno2\nhttps://vm.tiktok.com/TTPdrmKRQk/\n\n\nNew Merch - https://shopmrbeast.com\n----------------------------------------------------------------\nSubmit your videos here: https://www.beastreactssubmissions.com/\nfollow all of these or i will kick you\n• Facebook - https://www.facebook.com/MrBeast6000/\n• Twitter - https://twitter.com/MrBeast\n•  Instagram - https://www.instagram.com/mrbeast\n•  Instagram - https://www.instagram.com/beastreacts\n\n--------------------------------------------------------------------",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/L4KWhKY85cY/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/L4KWhKY85cY/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/L4KWhKY85cY/hqdefault.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "Beast Reacts",
        tags: [
          "life hacks",
          "crafts",
          "slime",
          "do it yourself",
          "diy",
          "lifehacks",
          "dily projects",
          "useful things",
          "how to",
          "experiment",
          "experiments",
          "diy activities",
          "handcraft",
          "prank",
          "funny",
          "challenge",
          "pranks",
          "secret",
          "diy slime",
          "laugh",
          "new",
          "skills",
          "tricks",
          "tips",
          "fun",
        ],
        categoryId: "24",
        liveBroadcastContent: "none",
        localized: {
          title: "Extreme Try Not To Laugh Challenge!",
          description:
            "Chris just won $10,000 BUT everytime he laughs, I spin a wheel where he could lose all his money!\n\nCHECK OUT THESE CHANNELS OR ELSE\nJifkin\nhttps://vm.tiktok.com/ZTdym3M3N/?k=1\n\nWilleezy Entertainment\nhttps://www.youtube.com/shorts/e0_bfc_1kCA\n\nLong-tax-77\nhttps://www.reddit.com/r/funnyvideos/comments/smtv72/bro_knows/\n\nPet.eles\nhttps://vm.tiktok.com/TTPdymG8xr/?k=1\n\nAuto_tuning_aksessuar\nhttps://www.instagram.com/reel/CYlYKGgMC8l/?utm_medium=copy_link\n\nSpace_walker24\nhttps://vm.tiktok.com/TTPdymbbdY/?k=1\n\nRound0range\nhttps://vm.tiktok.com/TTPdymTppU/?k=1\n\nSomewhiteguy690\nhttps://vm.tiktok.com/ZTdyupQRL/?k=1\n\nAwam..shuja\nhttps://vm.tiktok.com/ZTdymv1Ch/?k=1\n\nSpecere\nhttps://vm.tiktok.com/TTPdyuLWsc/?k=1\n\nFjerry\nhttps://vm.tiktok.com/TTPdyuLND5/?k=1\n\nKoresus\nhttps://vm.tiktok.com/ZTdymwyYM/?k=1\n\nKiddo480\nhttps://www.youtube.com/watch?v=9A1ZFSzXJ5U\n\nSammy Haig\nhttps://www.youtube.com/watch?v=COvju-gxCcw\n\nHanselsandovalr\nhttps://vm.tiktok.com/TTPdyuQMBw/?k=1\n\nTrippiedrob\nhttps://vm.tiktok.com/ZTdyua6NK/?k=1\n\nTheSyphon\nhttps://www.youtube.com/shorts/h5TeGqkw7MQ\n\nPreciseAnt76\nhttps://www.reddit.com/r/MemeVideos/comments/ss0t2r/can_you_lay_on_your_stomach/\n\n_sasuke\nhttps://www.reddit.com/r/MemeVideos/comments/qdc0tq/crip_walk/\n\nElforruso\nhttps://vm.tiktok.com/ZTdyuMojB/?k=1\n\nLstoast\nhttps://vm.tiktok.com/ZTdyuAWxV/?k=1\n\nVeysper\nhttps://vm.tiktok.com/ZTdyuQL1Y/?k=1\n\nDayyyumm_shorty\nhttps://vm.tiktok.com/TTPdyum4EF/?k=1\n\nOlejguy\nhttps://vm.tiktok.com/ZTdyumJJy/?k=1\n\nHoodshumor\nhttps://www.instagram.com/reel/CYm8Ah8F1qR/?utm_medium=copy_link\n\nJaysamuel1220\nhttps://www.youtube.com/watch?v=NoJTNebpk0I\n\n_Crotch_Goblin_\nhttps://www.reddit.com/r/dankvideos/comments/sjao3g/who_is_valve_guy_the_answer_was_right_infront_of/\n\nMikeymaybeme\nhttps://vm.tiktok.com/TTPdrmosGE/\n\nCarliejayes\nhttps://vm.tiktok.com/ZTdyucNNd/?k=1\n\nJamesmakesmusic\nhttps://vm.tiktok.com/ZTdyub1Gw/?k=1\n\nSmm_govno2\nhttps://vm.tiktok.com/TTPdrmKRQk/\n\n\nNew Merch - https://shopmrbeast.com\n----------------------------------------------------------------\nSubmit your videos here: https://www.beastreactssubmissions.com/\nfollow all of these or i will kick you\n• Facebook - https://www.facebook.com/MrBeast6000/\n• Twitter - https://twitter.com/MrBeast\n•  Instagram - https://www.instagram.com/mrbeast\n•  Instagram - https://www.instagram.com/beastreacts\n\n--------------------------------------------------------------------",
        },
        defaultAudioLanguage: "en",
      },
      contentDetails: {
        duration: "PT8M41S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "6571287",
        likeCount: "274399",
        favoriteCount: "0",
        commentCount: "7267",
      },
    },
    {
      kind: "youtube#video",
      etag: "akydiivzHwx3fYdLyM571Yh5GOY",
      id: "wufC1iDFqvI",
      snippet: {
        publishedAt: "2022-03-15T21:00:33Z",
        channelId: "UC1JHshGsMPlfLeiXxidterA",
        title: "Basketball Trivia Game Pt. 4 @Jenna Bandy",
        description: "#trivia #shorts",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/wufC1iDFqvI/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/wufC1iDFqvI/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/wufC1iDFqvI/hqdefault.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "Wafellow",
        tags: ["trivia"],
        categoryId: "24",
        liveBroadcastContent: "none",
        defaultLanguage: "en",
        localized: {
          title: "Basketball Trivia Game Pt. 4 @Jenna Bandy",
          description: "#trivia #shorts",
        },
        defaultAudioLanguage: "en",
      },
      contentDetails: {
        duration: "PT20S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "724281",
        likeCount: "31856",
        favoriteCount: "0",
        commentCount: "277",
      },
    },
    {
      kind: "youtube#video",
      etag: "c6L0Sn8RoTHbjSpGGwj1SEVG8wg",
      id: "UHiSc_M0xQU",
      snippet: {
        publishedAt: "2022-03-16T09:00:11Z",
        channelId: "UCuhAUMLzJxlP1W7mEk0_6lA",
        title: "[MV] 솔라 (Solar) - 꿀 (HONEY)",
        description:
          "[MV] 솔라 (Solar) - 꿀 (HONEY)\r\n\r\nInstagram: https://bit.ly/2TrQPJD\r\nFacebook: https://bit.ly/2OYoA1W\r\nTwitter: https://bit.ly/2TuKNbo\r\n\r\nAbout MAMAMOO.\r\nMAMAMOO(마마무) OFFICIAL CHANNEL\r\n\r\n#MAMAMOO #Solar #容\r\n\r\nMAMAMOO.\r\nSUBSCRIBE: https://bit.ly/2PFdfsI\r\nhttps://www.youtube.com/c/MAMAMOO_OFFICIAL\r\n\r\nDon't forget to subscribe, like and leave a comment.",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/UHiSc_M0xQU/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/UHiSc_M0xQU/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/UHiSc_M0xQU/hqdefault.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "MAMAMOO",
        tags: [
          "MAMAMOO",
          "마마무",
          "솔라",
          "마마무 솔라",
          "Solar",
          "솔라 꿀",
          "솔라 HONEY",
          "솔라 容",
          "솔라 FACE",
          "容:FACE",
          "꿀 (HONEY)",
          "솔라 뮤직비디오",
          "솔라 MV",
        ],
        categoryId: "10",
        liveBroadcastContent: "none",
        defaultLanguage: "ko",
        localized: {
          title: "[MV] 솔라 (Solar) - 꿀 (HONEY)",
          description:
            "[MV] 솔라 (Solar) - 꿀 (HONEY)\r\n\r\nInstagram: https://bit.ly/2TrQPJD\r\nFacebook: https://bit.ly/2OYoA1W\r\nTwitter: https://bit.ly/2TuKNbo\r\n\r\nAbout MAMAMOO.\r\nMAMAMOO(마마무) OFFICIAL CHANNEL\r\n\r\n#MAMAMOO #Solar #容\r\n\r\nMAMAMOO.\r\nSUBSCRIBE: https://bit.ly/2PFdfsI\r\nhttps://www.youtube.com/c/MAMAMOO_OFFICIAL\r\n\r\nDon't forget to subscribe, like and leave a comment.",
        },
        defaultAudioLanguage: "ko",
      },
      contentDetails: {
        duration: "PT2M54S",
        dimension: "2d",
        definition: "hd",
        caption: "true",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "3721732",
        likeCount: "233633",
        favoriteCount: "0",
        commentCount: "14530",
      },
    },
    {
      kind: "youtube#video",
      etag: "rBsXMeYmUayuYEAECJ4QYFqBydY",
      id: "NPnMIM6C0rY",
      snippet: {
        publishedAt: "2022-03-16T17:04:11Z",
        channelId: "UCIJwWYOfsCfz6PjxbONYXSg",
        title: "This is your sign to buy a workout onesie",
        description: "Get the Energy Onesie: https://bit.ly/energyonesie",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/NPnMIM6C0rY/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/NPnMIM6C0rY/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/NPnMIM6C0rY/hqdefault.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "blogilates",
        categoryId: "26",
        liveBroadcastContent: "none",
        defaultLanguage: "en",
        localized: {
          title: "This is your sign to buy a workout onesie",
          description: "Get the Energy Onesie: https://bit.ly/energyonesie",
        },
        defaultAudioLanguage: "en",
      },
      contentDetails: {
        duration: "PT1M",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: false,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "264953",
        likeCount: "27371",
        favoriteCount: "0",
        commentCount: "493",
      },
    },
    {
      kind: "youtube#video",
      etag: "Fgt3Oo0HRFsgVO_U7589f95HYt8",
      id: "JAA3bqbBras",
      snippet: {
        publishedAt: "2022-03-16T18:21:06Z",
        channelId: "UCzhSn5_QhPjA7TvcJS0JYlA",
        title: "Hat prank😂#shorts #prank",
        description: "",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/JAA3bqbBras/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/JAA3bqbBras/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/JAA3bqbBras/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/JAA3bqbBras/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/JAA3bqbBras/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "QYLEK shorts🩳",
        categoryId: "22",
        liveBroadcastContent: "none",
        localized: {
          title: "Hat prank😂#shorts #prank",
          description: "",
        },
      },
      contentDetails: {
        duration: "PT11S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: false,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "4244818",
        likeCount: "120534",
        favoriteCount: "0",
        commentCount: "247",
      },
    },
    {
      kind: "youtube#video",
      etag: "cbxkEw-nKNv1uFOEM4V-NYHqQzM",
      id: "bHNzEwQdEUs",
      snippet: {
        publishedAt: "2022-03-15T21:03:23Z",
        channelId: "UChRlaISXbl2gECFAmDzxgzg",
        title: "I Bought a Bronco to Lightly Off-Road",
        description:
          "I bought a ford bronco for some offroad fun.\n\nADD ME ON\nInstagram: https://www.instagram.com/westengw​​\nFacebook: https://www.facebook.com/westengw",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/bHNzEwQdEUs/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/bHNzEwQdEUs/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/bHNzEwQdEUs/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/bHNzEwQdEUs/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/bHNzEwQdEUs/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Westen Champlin",
        categoryId: "2",
        liveBroadcastContent: "none",
        defaultLanguage: "en",
        localized: {
          title: "I Bought a Bronco to Lightly Off-Road",
          description:
            "I bought a ford bronco for some offroad fun.\n\nADD ME ON\nInstagram: https://www.instagram.com/westengw​​\nFacebook: https://www.facebook.com/westengw",
        },
        defaultAudioLanguage: "en",
      },
      contentDetails: {
        duration: "PT10M21S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "777765",
        likeCount: "50520",
        favoriteCount: "0",
        commentCount: "2238",
      },
    },
    {
      kind: "youtube#video",
      etag: "NlL17QixN9j9yEP-8KHJuAcmbA0",
      id: "MkFRdOg_oxU",
      snippet: {
        publishedAt: "2022-03-15T03:56:27Z",
        channelId: "UCJ5v_MCY6GNUBTO8-D3XoAg",
        title:
          "WWE says goodbye to the bad guy with a touching tribute to Scott Hall",
        description:
          "From the bad guy persona to to N.W.O and beyond, WWE remembers and honors the tremendous legacy of WWE Hall of Famer Scott Hall.\nStream WWE on Peacock https://pck.tv/3l4d8TP in the U.S. and on WWE Network http://wwe.yt/wwenetwork everywhere else\r\n---------------------------------------------------------------------\r\nFollow WWE on YouTube for more exciting action!\r\n---------------------------------------------------------------------\r\nSubscribe to WWE on YouTube: http://wwe.yt/\r\nCheck out WWE.com for news and updates: http://goo.gl/akf0J4\r\nWatch WWE on Sony in India: http://www.wwe.com/SonySportsNetwork\r\nWatch WWE on Disney+ Hotstar in Indonesia: http://www.wwe.com/hotstar\r\nFind the latest Superstar gear at WWEShop: http://shop.wwe.com\r\n---------------------------------------------\r\nCheck out our other channels!\r\n---------------------------------------------\r\nThe Bella Twins: https://www.youtube.com/thebellatwins\r\nUpUpDownDown: https://www.youtube.com/upupdowndown\r\nWWEMusic: https://www.youtube.com/wwemusic\r\nTotal Divas: https://www.youtube.com/wwetotaldivas\r\n------------------------------------\r\nWWE on Social Media\r\n------------------------------------\r\nTwitter: https://twitter.com/wwe\r\nFacebook: https://www.facebook.com/wwe\r\nInstagram: https://www.instagram.com/wwe/\r\nGiphy: https://giphy.com/wwe\r\n------------------------------------",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/MkFRdOg_oxU/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/MkFRdOg_oxU/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/MkFRdOg_oxU/hqdefault.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "WWE",
        tags: [
          "Hulk Hogan",
          "Kevin Nash",
          "Razor Ramon",
          "Scott Hall",
          "Shawn Michaels",
          "Triple H",
          "X-Pac",
          "superstars",
          "world wrestling entertainment",
          "wrestle",
          "wrestler",
          "wrestling",
          "wwe",
          "wwe 2021",
          "مصارعه",
          "कुश्ती",
          "डब्लू डब्लू ई",
          "पहलवान",
          "मैच",
          "व्यावसायिक कुश्ती",
          "सुपरस्टार",
          "scott hall wwe",
          "razor ramon wwe",
          "scott hall wcw",
        ],
        categoryId: "17",
        liveBroadcastContent: "none",
        localized: {
          title:
            "WWE says goodbye to the bad guy with a touching tribute to Scott Hall",
          description:
            "From the bad guy persona to to N.W.O and beyond, WWE remembers and honors the tremendous legacy of WWE Hall of Famer Scott Hall.\nStream WWE on Peacock https://pck.tv/3l4d8TP in the U.S. and on WWE Network http://wwe.yt/wwenetwork everywhere else\r\n---------------------------------------------------------------------\r\nFollow WWE on YouTube for more exciting action!\r\n---------------------------------------------------------------------\r\nSubscribe to WWE on YouTube: http://wwe.yt/\r\nCheck out WWE.com for news and updates: http://goo.gl/akf0J4\r\nWatch WWE on Sony in India: http://www.wwe.com/SonySportsNetwork\r\nWatch WWE on Disney+ Hotstar in Indonesia: http://www.wwe.com/hotstar\r\nFind the latest Superstar gear at WWEShop: http://shop.wwe.com\r\n---------------------------------------------\r\nCheck out our other channels!\r\n---------------------------------------------\r\nThe Bella Twins: https://www.youtube.com/thebellatwins\r\nUpUpDownDown: https://www.youtube.com/upupdowndown\r\nWWEMusic: https://www.youtube.com/wwemusic\r\nTotal Divas: https://www.youtube.com/wwetotaldivas\r\n------------------------------------\r\nWWE on Social Media\r\n------------------------------------\r\nTwitter: https://twitter.com/wwe\r\nFacebook: https://www.facebook.com/wwe\r\nInstagram: https://www.instagram.com/wwe/\r\nGiphy: https://giphy.com/wwe\r\n------------------------------------",
        },
      },
      contentDetails: {
        duration: "PT2M55S",
        dimension: "2d",
        definition: "hd",
        caption: "true",
        licensedContent: true,
        regionRestriction: {
          blocked: ["RU"],
        },
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "2497879",
        likeCount: "74025",
        favoriteCount: "0",
        commentCount: "6170",
      },
    },
    {
      kind: "youtube#video",
      etag: "YpU9bJq4TI3ArgYu0OliP4rn1EI",
      id: "hASVM1BUZys",
      snippet: {
        publishedAt: "2022-03-16T06:39:52Z",
        channelId: "UCba8p0lVr5UeZNSblCEC4yw",
        title: "Are The Songs Funny 🤔",
        description:
          "Are The Songs Funny 🤔\n\nVideo Credit: @JT Casey \n\nContact My Socials If You Own This Video And Want It Removed :)\n\nIf you want to see more Minecraft make sure to blow up this post!\nStalk me on Twitch!\nStreaming LIVE on Twitch sometimes:\n https://www.twitch.tv/vape\nTwitter: https://twitter.com/rlvape\nDiscord: https://discord.gg/6N7bN9​​​\nTikTok: @Vaupaye\n\n#shorts #vaupaye #trynottolaugh",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/hASVM1BUZys/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/hASVM1BUZys/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/hASVM1BUZys/hqdefault.jpg",
            width: 480,
            height: 360,
          },
        },
        channelTitle: "Vaupaye",
        tags: [
          "vaupaye",
          "try not to laugh",
          "try not to laugh challenge",
          "do you know this song",
          "tiktok songs",
          "guess the song",
          "are the songs funny",
        ],
        categoryId: "24",
        liveBroadcastContent: "none",
        localized: {
          title: "Are The Songs Funny 🤔",
          description:
            "Are The Songs Funny 🤔\n\nVideo Credit: @JT Casey \n\nContact My Socials If You Own This Video And Want It Removed :)\n\nIf you want to see more Minecraft make sure to blow up this post!\nStalk me on Twitch!\nStreaming LIVE on Twitch sometimes:\n https://www.twitch.tv/vape\nTwitter: https://twitter.com/rlvape\nDiscord: https://discord.gg/6N7bN9​​​\nTikTok: @Vaupaye\n\n#shorts #vaupaye #trynottolaugh",
        },
      },
      contentDetails: {
        duration: "PT23S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: false,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "803215",
        likeCount: "53560",
        favoriteCount: "0",
        commentCount: "596",
      },
    },
    {
      kind: "youtube#video",
      etag: "L6Y1tkkEHXJ7iyAwiDCjHBKwG4c",
      id: "-tOhx3scJvU",
      snippet: {
        publishedAt: "2022-03-14T19:00:24Z",
        channelId: "UCtNdVINwfYFTQEEZgMiQ8FA",
        title:
          "*im back* When Blaming it on the baby is a good idea - Sharon kinne | Mystery & Makeup Bailey Sarian",
        description:
          "This video is sponsored by Best Fiends. Download Best Fiends for FREE: https://seriously.onelink.me/22957857/BaileySarian032022 and get $5 worth of gold and energy for FREE if you beat level 5!\n\n________\n\nHi friends, I missed you! Thank you for your patience my life has been a hot mess but I’m here now and I’m so happy. Todays story blew my mind, Sharon Sharon SHARONNNN!! You crazy azz lady…. \n\nLet me know who you want me to talk about next week!!! I love and appreciate you \nX O\nBailey Sarian \n__________ \n\n\n:  :    F O L L O W    M E     :  :\n\nDiscord : http://discord.gg/baileysarian\nTik Tok : BaileySarian\nInstagram : http://bit.ly/2nbO4PR\nFacebook : http://bit.ly/2mdZtK6\nTwitter : http://bit.ly/2yT4BLV\nPinterest : http://bit.ly/2mVpXnY\nYoutube : http://bit.ly/1HGw3Og\nSnapchat : BaileySarian \n\n\nRECOMMEND A STORY HERE : cases4bailey@gmail.com \n\nBusiness Related Emails : Baileysarianteam@wmeagency.com\n\n___________\n\n:  :    P R O D U C T S     U S E D    :  : \n\nFACE\n\nMAKE UP FOR EVER HD Skin Undetectable Longwear Foundation - 1Y04 Warm Alabaster & 4R76 Cool Ebony (for contour\nhttps://shop-links.co/cgMBkJsf8PH\n\nKVD Beauty Good Apple Lightweight Full-Coverage Concealer - Medium 149\nhttps://shop-links.co/cgMBl2QMVVw\n\nJouer Cosmetics Essential High Coverage Liquid Concealer - Crème\nhttps://shop-links.co/cgMBm4ZLqCb\n\nMaybelline Fit Me Loose Finishing Powder - Fair Light 10\nhttps://shop-links.co/cgMBo95Fiis\n\nScott Barnes Sculpting And Contour N°1 - Contour Palette\nhttps://shop-links.co/cgMBpVPR3YZ\n\nSEPHORA COLLECTION Golden Hour Highlighter Duo - Daybreak\nhttps://shop-links.co/cgMBrdFzCzr\n\nColourpop Pressed Powder Blush - Retro\nhttps://shop-links.co/cgMBr6LJ5IX\n\nBROWS\n\nPatrick Ta Major Brow Shaping Wax - Clear\nhttps://shop-links.co/cgMBEojiO2f\n\nMAKE UP FOR EVER Aqua Resist Waterproof Eyebrow Definer Pencil - Dark Brown\nhttps://shop-links.co/cgMBIf2vhIE\n\nEYES\n\nNARS Smudge Proof Eyeshadow Base\nhttps://shop-links.co/cgMBJqPWnsj\n\nKVD Lolita Por Vida Eyeshadow Palette\nhttps://shop-links.co/cgMBKkCtoVU\n\nMAKE UP FOR EVER Aqua Resist Color Pencil Eyeliner - 05 Bronze\nhttps://shop-links.co/cgMBLbN5n4v\n\nMakeup Geek Matte Eyeshadow - Spilled Tea\nhttps://shop-links.co/cgMBMn3LG4U\nMAC M·A·CStack Mascara\nhttps://shop-links.co/cgMBNLk5Zib\n\nAngel Wings J-Lash Natural Wispy Lashes - Wispy 03\nhttps://shop-links.co/cgMBP0R1UxY\n\nLIPS\n\nHUDA BEAUTY Liquid Matte Ultra-Comfort Transfer-Proof Lipstick - Famous\nhttps://shop-links.co/cgMBVa2ToSJ\n\nNARS Lipstick - Honolulu Honey\nhttps://shop-links.co/cgMBVX9MMaJ\n\n♡ \n*These links are affiliate links. which means, if you click on the link and purchase product, a small percentage comes back to me. It helps me keep on keepin on with my videos and I appreciate you if you choose to support. If you don’t, that’s ok too.",
        thumbnails: {
          default: {
            url: "https://i.ytimg.com/vi/-tOhx3scJvU/default.jpg",
            width: 120,
            height: 90,
          },
          medium: {
            url: "https://i.ytimg.com/vi/-tOhx3scJvU/mqdefault.jpg",
            width: 320,
            height: 180,
          },
          high: {
            url: "https://i.ytimg.com/vi/-tOhx3scJvU/hqdefault.jpg",
            width: 480,
            height: 360,
          },
          standard: {
            url: "https://i.ytimg.com/vi/-tOhx3scJvU/sddefault.jpg",
            width: 640,
            height: 480,
          },
          maxres: {
            url: "https://i.ytimg.com/vi/-tOhx3scJvU/maxresdefault.jpg",
            width: 1280,
            height: 720,
          },
        },
        channelTitle: "Bailey Sarian",
        tags: [
          "Bailey sarian",
          "youtube bailey sarian",
          "bailey sarian youtube",
          "youtube bailey",
          "bailey",
          "sarian",
          "mystery makeup monday",
          "monday mystery makeup",
          "mystery makeup",
          "mystery makeup mondays",
          "makeup artist",
          "makeup 2021",
          "new makeup 2021",
          "new makeup tutorial",
          "flawless makeup",
          "makeup and story time",
          "makeup story time",
          "story time and makeup",
          "story time",
          "grwm",
          "grwm and makeup",
          "get ready with me and makeup",
          "makeup grwm",
          "grwm 2021",
          "flawless foundation",
          "mystery monday",
          "mystery",
          "monday story time",
        ],
        categoryId: "24",
        liveBroadcastContent: "none",
        defaultLanguage: "en",
        localized: {
          title:
            "*im back* When Blaming it on the baby is a good idea - Sharon kinne | Mystery & Makeup Bailey Sarian",
          description:
            "This video is sponsored by Best Fiends. Download Best Fiends for FREE: https://seriously.onelink.me/22957857/BaileySarian032022 and get $5 worth of gold and energy for FREE if you beat level 5!\n\n________\n\nHi friends, I missed you! Thank you for your patience my life has been a hot mess but I’m here now and I’m so happy. Todays story blew my mind, Sharon Sharon SHARONNNN!! You crazy azz lady…. \n\nLet me know who you want me to talk about next week!!! I love and appreciate you \nX O\nBailey Sarian \n__________ \n\n\n:  :    F O L L O W    M E     :  :\n\nDiscord : http://discord.gg/baileysarian\nTik Tok : BaileySarian\nInstagram : http://bit.ly/2nbO4PR\nFacebook : http://bit.ly/2mdZtK6\nTwitter : http://bit.ly/2yT4BLV\nPinterest : http://bit.ly/2mVpXnY\nYoutube : http://bit.ly/1HGw3Og\nSnapchat : BaileySarian \n\n\nRECOMMEND A STORY HERE : cases4bailey@gmail.com \n\nBusiness Related Emails : Baileysarianteam@wmeagency.com\n\n___________\n\n:  :    P R O D U C T S     U S E D    :  : \n\nFACE\n\nMAKE UP FOR EVER HD Skin Undetectable Longwear Foundation - 1Y04 Warm Alabaster & 4R76 Cool Ebony (for contour\nhttps://shop-links.co/cgMBkJsf8PH\n\nKVD Beauty Good Apple Lightweight Full-Coverage Concealer - Medium 149\nhttps://shop-links.co/cgMBl2QMVVw\n\nJouer Cosmetics Essential High Coverage Liquid Concealer - Crème\nhttps://shop-links.co/cgMBm4ZLqCb\n\nMaybelline Fit Me Loose Finishing Powder - Fair Light 10\nhttps://shop-links.co/cgMBo95Fiis\n\nScott Barnes Sculpting And Contour N°1 - Contour Palette\nhttps://shop-links.co/cgMBpVPR3YZ\n\nSEPHORA COLLECTION Golden Hour Highlighter Duo - Daybreak\nhttps://shop-links.co/cgMBrdFzCzr\n\nColourpop Pressed Powder Blush - Retro\nhttps://shop-links.co/cgMBr6LJ5IX\n\nBROWS\n\nPatrick Ta Major Brow Shaping Wax - Clear\nhttps://shop-links.co/cgMBEojiO2f\n\nMAKE UP FOR EVER Aqua Resist Waterproof Eyebrow Definer Pencil - Dark Brown\nhttps://shop-links.co/cgMBIf2vhIE\n\nEYES\n\nNARS Smudge Proof Eyeshadow Base\nhttps://shop-links.co/cgMBJqPWnsj\n\nKVD Lolita Por Vida Eyeshadow Palette\nhttps://shop-links.co/cgMBKkCtoVU\n\nMAKE UP FOR EVER Aqua Resist Color Pencil Eyeliner - 05 Bronze\nhttps://shop-links.co/cgMBLbN5n4v\n\nMakeup Geek Matte Eyeshadow - Spilled Tea\nhttps://shop-links.co/cgMBMn3LG4U\nMAC M·A·CStack Mascara\nhttps://shop-links.co/cgMBNLk5Zib\n\nAngel Wings J-Lash Natural Wispy Lashes - Wispy 03\nhttps://shop-links.co/cgMBP0R1UxY\n\nLIPS\n\nHUDA BEAUTY Liquid Matte Ultra-Comfort Transfer-Proof Lipstick - Famous\nhttps://shop-links.co/cgMBVa2ToSJ\n\nNARS Lipstick - Honolulu Honey\nhttps://shop-links.co/cgMBVX9MMaJ\n\n♡ \n*These links are affiliate links. which means, if you click on the link and purchase product, a small percentage comes back to me. It helps me keep on keepin on with my videos and I appreciate you if you choose to support. If you don’t, that’s ok too.",
        },
        defaultAudioLanguage: "en",
      },
      contentDetails: {
        duration: "PT40M42S",
        dimension: "2d",
        definition: "hd",
        caption: "false",
        licensedContent: true,
        contentRating: {},
        projection: "rectangular",
      },
      statistics: {
        viewCount: "1510550",
        likeCount: "109761",
        favoriteCount: "0",
        commentCount: "10373",
      },
    },
  ],
  nextPageToken: "CBkQAA",
  pageInfo: {
    totalResults: 200,
    resultsPerPage: 25,
  },
};
